language: python
python:
  - "3.6"
  - "3.7"
install:
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls
script: 
  - pip install coverage==4.5.4
  - git clone https://github.com/kungkingc/SOS-shoppingCart.git
  - pytest --cov=SOS-shoppingCart/test.py
after_success:
   - coveralls
