language: python
python:
  - "3.7"
install:
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls
script: 
  - pip install coverage==4.5.4
  - git clone https://github.com/kungkingc/SOS-shoppingCart.git
  - cd SOS-shoppingCart
  - pytest --cov=Cart --cov=Product --cov=Main
  #- py.test test.py --cov='.'
after_success:
   - coveralls
